title: Fun With Computers
description: >-
  Computers can be incredibly useful and incredibly silly.
  If we're lucky, this happens simultaneously.

url: "https://timcheeseman.com"
baseurl: "/funwithcomputers"
github_url: "https://github.com/cirla/funwithcomputers"

author: Tim Cheeseman
email: tim@timcheeseman.com
github_username:  cirla
twitter_username: tim_cheeseman
google_analytics: UA-60152626-4

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

encoding: utf-8
sass:
    style: :compressed
timezone: America/New_York

